import { Product, Category, Brand, User, Order } from '@/types';

export const initialUsers: User[] = [
  {
    _id: 'user-admin-1',
    name: 'Admin Luxora',
    email: 'admin@luxora.com',
    role: 'Admin',
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'user-admin-2',
    name: 'Ronny Admin',
    email: 'ronythessery@gmail.com',
    role: 'Admin',
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'user-customer-1',
    name: 'Ronny Customer',
    email: 'ronny@gmail.com',
    role: 'Customer',
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'user-customer-2',
    name: 'Sarah Connor',
    email: 'sarah@example.com',
    role: 'Customer',
    status: 'active',
    createdAt: new Date().toISOString(),
  },
];

export const initialCategories: Category[] = [
  {
    _id: 'cat-1',
    name: 'Dresses',
    slug: 'dresses',
    description: 'Elegant evening and casual luxury dresses',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop',
    status: 'active',
  },
  {
    _id: 'cat-2',
    name: 'Outerwear',
    slug: 'outerwear',
    description: 'Tailored coats, blazers, and luxury leather jackets',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=800&auto=format&fit=crop',
    status: 'active',
  },
  {
    _id: 'cat-3',
    name: 'Footwear',
    slug: 'footwear',
    description: 'Handcrafted leather boots and premium heels',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
    status: 'active',
  },
  {
    _id: 'cat-4',
    name: 'Accessories',
    slug: 'accessories',
    description: 'Luxury handbags, belts, and designer accessories',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    status: 'active',
  },
];

export const initialBrands: Brand[] = [
  {
    _id: 'brand-1',
    name: 'LUXORA COUTURE',
    description: 'Signature haute couture and modern statement pieces',
    status: 'active',
  },
  {
    _id: 'brand-2',
    name: 'NOIR STUDIO',
    description: 'Minimalist monochrome tailoring and modern street luxury',
    status: 'active',
  },
  {
    _id: 'brand-3',
    name: 'SQUARE ESSENTIAL',
    description: 'Timeless wardrobe staples built with premium fabrics',
    status: 'active',
  },
  {
    _id: 'brand-4',
    name: 'AURA ELEGANCE',
    description: 'Graceful silhouettes and silk essentials',
    status: 'active',
  },
];

export const initialProducts: Product[] = [
  {
    _id: 'prod-1',
    name: 'Silk Evening Gown',
    slug: 'silk-evening-gown',
    description: 'Exquisite floor-length silk gown crafted with hand-finished pleats and subtle sheen.',
    price: 450,
    originalPrice: 520,
    discountPercent: 13,
    rating: 4.9,
    reviewCount: 24,
    colors: ['Black', 'Emerald', 'Burgundy'],
    isFeatured: true,
    isSoldOut: false,
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-1',
    brandId: 'brand-1',
    status: 'active',
  },
  {
    _id: 'prod-2',
    name: 'Classic Leather Biker Jacket',
    slug: 'classic-leather-biker-jacket',
    description: 'Handcrafted full-grain nappa leather jacket with asymmetric silver hardware.',
    price: 380,
    originalPrice: 450,
    discountPercent: 15,
    rating: 4.8,
    reviewCount: 38,
    colors: ['Black', 'Dark Brown'],
    isFeatured: true,
    isSoldOut: false,
    stock: 8,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-2',
    brandId: 'brand-2',
    status: 'active',
  },
  {
    _id: 'prod-3',
    name: 'Minimalist Linen Blazer',
    slug: 'minimalist-linen-blazer',
    description: 'Lightweight unstructured linen blazer designed for effortless warm-weather sophistication.',
    price: 290,
    originalPrice: 340,
    discountPercent: 14,
    rating: 4.7,
    reviewCount: 19,
    colors: ['Beige', 'White', 'Charcoal'],
    isFeatured: false,
    isSoldOut: false,
    stock: 22,
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-2',
    brandId: 'brand-3',
    status: 'active',
  },
  {
    _id: 'prod-4',
    name: 'Designer Leather Handbag',
    slug: 'designer-leather-handbag',
    description: 'Structured calfskin tote bag with custom gold-plated hardware and suede interior.',
    price: 620,
    originalPrice: 750,
    discountPercent: 17,
    rating: 5.0,
    reviewCount: 42,
    colors: ['Black', 'Tan', 'Cream'],
    isFeatured: true,
    isSoldOut: false,
    stock: 5,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-4',
    brandId: 'brand-4',
    status: 'active',
  },
  {
    _id: 'prod-5',
    name: 'Structured Oversized Coat',
    slug: 'structured-oversized-coat',
    description: 'Double-breasted virgin wool trench coat with bold lapels and removable belt.',
    price: 540,
    originalPrice: 620,
    discountPercent: 12,
    rating: 4.9,
    reviewCount: 29,
    colors: ['Camel', 'Black'],
    isFeatured: true,
    isSoldOut: false,
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-2',
    brandId: 'brand-1',
    status: 'active',
  },
  {
    _id: 'prod-6',
    name: 'Chelsea Leather Boots',
    slug: 'chelsea-leather-boots',
    description: 'Italian leather ankle boots featuring Goodyear welted sole and elastic side gussets.',
    price: 320,
    originalPrice: 380,
    discountPercent: 15,
    rating: 4.6,
    reviewCount: 16,
    colors: ['Black', 'Dark Espresso'],
    isFeatured: false,
    isSoldOut: false,
    stock: 18,
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-3',
    brandId: 'brand-2',
    status: 'active',
  },
  {
    _id: 'prod-7',
    name: 'Silk Pleated Midi Dress',
    slug: 'silk-pleated-midi-dress',
    description: 'Fluid pleated midi dress crafted from pure mulberry silk with cinched waist detailing.',
    price: 410,
    originalPrice: 480,
    discountPercent: 14,
    rating: 4.8,
    reviewCount: 21,
    colors: ['Ruby Red', 'Champagne'],
    isFeatured: true,
    isSoldOut: false,
    stock: 10,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-1',
    brandId: 'brand-4',
    status: 'active',
  },
  {
    _id: 'prod-8',
    name: 'Monochrome Knit Sweater',
    slug: 'monochrome-knit-sweater',
    description: 'Heavyweight cashmere-blend ribbed sweater with relaxed mock neck silhouette.',
    price: 180,
    originalPrice: 220,
    discountPercent: 18,
    rating: 4.5,
    reviewCount: 31,
    colors: ['Off-White', 'Slate Grey'],
    isFeatured: false,
    isSoldOut: false,
    stock: 25,
    images: [
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-2',
    brandId: 'brand-3',
    status: 'active',
  },
  {
    _id: 'prod-9',
    name: 'Velvet Cocktail Blazer',
    slug: 'velvet-cocktail-blazer',
    description: 'Plush cotton velvet blazer with satin peak lapels and structured shoulder line.',
    price: 340,
    originalPrice: 390,
    discountPercent: 12,
    rating: 4.8,
    reviewCount: 17,
    colors: ['Midnight Blue', 'Emerald'],
    isFeatured: true,
    isSoldOut: false,
    stock: 14,
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-2',
    brandId: 'brand-1',
    status: 'active',
  },
  {
    _id: 'prod-10',
    name: 'Italian Leather Loafers',
    slug: 'italian-leather-loafers',
    description: 'Hand-burnished calfskin penny loafers featuring stacked leather heels and cushioned footbed.',
    price: 280,
    originalPrice: 330,
    discountPercent: 15,
    rating: 4.7,
    reviewCount: 22,
    colors: ['Dark Mahogany', 'Black'],
    isFeatured: true,
    isSoldOut: false,
    stock: 9,
    images: [
      'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-3',
    brandId: 'brand-3',
    status: 'active',
  },
  {
    _id: 'prod-11',
    name: 'Minimalist Gold Wristwatch',
    slug: 'minimalist-gold-wristwatch',
    description: 'Precision Japanese movement watch with 18k gold-plated bezel and sapphire crystal face.',
    price: 490,
    originalPrice: 580,
    discountPercent: 15,
    rating: 4.9,
    reviewCount: 54,
    colors: ['Gold / Black', 'Rose Gold'],
    isFeatured: true,
    isSoldOut: false,
    stock: 7,
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-4',
    brandId: 'brand-4',
    status: 'active',
  },
  {
    _id: 'prod-12',
    name: 'Tailored Wide-Leg Trousers',
    slug: 'tailored-wide-leg-trousers',
    description: 'High-waisted wool blend trousers with front pleats and fluid wide-leg silhouette.',
    price: 210,
    originalPrice: 250,
    discountPercent: 16,
    rating: 4.6,
    reviewCount: 18,
    colors: ['Ivory', 'Black'],
    isFeatured: false,
    isSoldOut: false,
    stock: 20,
    images: [
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-2',
    brandId: 'brand-2',
    status: 'active',
  },
  {
    _id: 'prod-13',
    name: 'Satin Slip Midi Dress',
    slug: 'satin-slip-midi-dress',
    description: 'Bias-cut silk satin slip dress with adjustable delicate straps and cowl neckline.',
    price: 260,
    originalPrice: 310,
    discountPercent: 16,
    rating: 4.8,
    reviewCount: 33,
    colors: ['Emerald Green', 'Black', 'Pearl'],
    isFeatured: true,
    isSoldOut: false,
    stock: 11,
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-1',
    brandId: 'brand-4',
    status: 'active',
  },
  {
    _id: 'prod-14',
    name: 'Polarized Acetate Sunglasses',
    slug: 'polarized-acetate-sunglasses',
    description: 'Hand-crafted Japanese acetate sunglasses with 100% UV protection polarized lenses.',
    price: 190,
    originalPrice: 230,
    discountPercent: 17,
    rating: 4.7,
    reviewCount: 28,
    colors: ['Black Tortoise', 'Gold Amber'],
    isFeatured: false,
    isSoldOut: false,
    stock: 30,
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-4',
    brandId: 'brand-2',
    status: 'active',
  },
  {
    _id: 'prod-15',
    name: 'Suede Ankle Boots',
    slug: 'suede-ankle-boots',
    description: 'Soft calf suede ankle boots with block heel and side zip closure.',
    price: 310,
    originalPrice: 360,
    discountPercent: 14,
    rating: 4.6,
    reviewCount: 15,
    colors: ['Tan Suede', 'Taupe'],
    isFeatured: false,
    isSoldOut: false,
    stock: 16,
    images: [
      'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-3',
    brandId: 'brand-3',
    status: 'active',
  },
  {
    _id: 'prod-16',
    name: 'Wool Cashmere Wrap Scarf',
    slug: 'wool-cashmere-wrap-scarf',
    description: 'Ultra-soft oversized cashmere-blend knitted scarf with fringed edges.',
    price: 140,
    originalPrice: 175,
    discountPercent: 20,
    rating: 4.9,
    reviewCount: 40,
    colors: ['Camel', 'Oatmeal'],
    isFeatured: false,
    isSoldOut: false,
    stock: 40,
    images: [
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?q=80&w=800&auto=format&fit=crop',
    ],
    categoryId: 'cat-4',
    brandId: 'brand-1',
    status: 'active',
  },
];

export const initialOrders: Order[] = [];
